cells=c(1,3,5,7,8,9,11,12,14)
rnameS=c("Row1","row2","row3")
cnameS=c("col1","col2","col3")
m2=matrix(cells,nrow=3,ncol=3,byrow=TRUE,dimnames=list(rnameS,cnameS))
print("3*3 matrix with label,filled by rows:")
print(m2)
print("3*3 matrix with label,filled by columns:")
m3=matrix(cells,nrow=3,ncol=3,byrow=FALSE,dimnames=list(rnameS,cnameS))
print(m3)
